name: churn-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - notebook
  - scipy
  - statsmodels
  - pip

  - pip:
      - xgboost
      - lightgbm
      - imbalanced-learn
      - streamlit
      - shap
